- src/main/kotlin/wu/seal/jsontokotlin/GenerateKotlinFileAction.kt
- src/main/kotlin/wu/seal/jsontokotlin/MakeKotlinClassAction.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
All tests have been tested and are passed
> Enhancement as per #45

- .travis.yml
- README.md
At the moment, the deployment workflow may be as following:
1. Run `./gradlew test` to ensure that all the unit tests passed
2. Run `./gradlew buildPlugin` to build the plugin
3. Commit changes, run `git tag v4.0-alpha`, and `git push --tags` to tag the commit
3. Open GitHub repository webpage, "draft a new release" and upload the `.zip` file
Now since we have already introduced travis-ci, we can automate this workflow:
1. Commit and push changes, run `git tag <any-tag>` such as `git tag v4.0-alpha` and `git push --tags`
2. Done!! Travis will do the rest.
@wuseal after merging my PR, remember to 
- Create your own **GitHub oauth token** in order to upload  the `.zip` file to GitHub 
```yml
api_key:
secure: H5mdQNsY/ihYOgY7NF58ahJKjMfl2j7rgtD1HPhk6s3zWrB4TwgRXy3rngSuhn7GfF5LxFe788Vk4WdWcqSr …
```
> Fasten deployment workflow

- .travis.yml
- build.gradle
As per #50 
After merging this PR, don't forget to replace the secure token with your own:
FYI, you can run the following command to generate the two tokens:
```shell
$ travis encrypt username="<your intellij username>"
$ travis encrypt password="<your intellij password>"
```
and replace the following content with your own tokens
```yml
env:
global:
- secure:
- secure:
```
Thanks :)
> Update publishing workflow

- .travis.yml
- build.gradle
> Automate publishing workflow

- src/main/kotlin/wu/seal/jsontokotlin/ConfigManager.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/InterceptorManager.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/MakeKeywordNamedPropertyValidInterceptor.kt
- src/main/kotlin/wu/seal/jsontokotlin/test/TestConfig.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/SettingsOtherTab.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/keywordsUtil.kt
- src/test/kotlin/wu/seal/jsontokotlin/interceptor/MakeKeywordNamedPropertyValidInterceptorTest.kt
As in [#74](https://github.com/wuseal/JsonToKotlinClass/issues/74)
> Making Kotlin Keywords valid as property name

- src/main/kotlin/wu/seal/jsontokotlin/GenerateKotlinFileAction.kt
- src/main/kotlin/wu/seal/jsontokotlin/MakeKotlinClassAction.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
As per #76 , since we have already two sources of JSON (Text and Url) and we are adding another one (File), I try to rearrange the input dialog, here is the new input dialog:
All unit tests are passed, what do you think? @wuseal
> Fix Issue#76

- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
Check whether the content in selected file is a valid JSON string
> optimization: validate json file

- src/main/kotlin/wu/seal/jsontokotlin/KotlinDataClassCodeMaker.kt
- src/main/kotlin/wu/seal/jsontokotlin/KotlinDataClassMaker.kt
- src/main/kotlin/wu/seal/jsontokotlin/MakeKotlinClassAction.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/KotlinDataClassFileGenerator.kt
- src/test/kotlin/wu/seal/jsontokotlin/KotlinDataClassMakerTest.kt
- src/test/kotlin/wu/seal/jsontokotlin/utils/classblockparse/ClassCodeParserTest.kt
#82 Fix issue
Change:
Reused KotlinDataClassFileGenerator() and changed the flow to create the list of non duplicate classes for inclass JsonToKotlin Conversion
> Fix issue#82

- README.md
- doc_for_json_sources.md
- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
> add doc and fix bug

- src/main/kotlin/extensions/wu/seal/PropertyPrefixSupport.kt
- src/main/kotlin/extensions/wu/seal/PropertySuffixSupport.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/ExtensionsTab.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
resolve #114 and resolve #109 And optimize usage experience
> 3.0.1 update ui

- README.md
- src/main/kotlin/wu/seal/jsontokotlin/ui/AdvancedAnnotationTab.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/AdvancedDialog.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/AdvancedOtherTab.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/AdvancedPropertyTab.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
Resolve #125 refactored 'settings' to 'advanced' in Pop Up Dialog
> refactored 'settings' to 'advanced' in Pop Up Dialog

- .gitignore
- src/main/kotlin/wu/seal/jsontokotlin/utils/Extensions.kt
- src/test/kotlin/wu/seal/jsontokotlin/regression/Issue121Test.kt
- src/test/kotlin/wu/seal/jsontokotlin/utils/ExtensionsKtTest.kt
resolve #121 
Kotlin Data Class don't generated as expected
> [Fix]  Kotlin Data Class don't generated as expected 

- src/main/kotlin/wu/seal/jsontokotlin/GenerateKotlinFileAction.kt
- src/main/kotlin/wu/seal/jsontokotlin/KotlinCodeMaker.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/ClassCodeFilter.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/KotlinDataClassFileGenerator.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/TypeHelper.kt
> 3.2.0 optimize/code optimize

- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
- src/test/kotlin/wu/seal/jsontokotlin/regression/Issue130Test.kt
> [Fix] disable gson html escaping to fix format error

- src/main/kotlin/wu/seal/jsontokotlin/feedback/CacheDirProvider.kt
- src/main/kotlin/wu/seal/jsontokotlin/feedback/PersistCache.kt
Added additional class to provide cache directory.
It used directly, because no approach for IoC presented here.
> Fix #139 Folder .jsontokotlin in $HOME

- src/main/resources/META-INF/plugin.xml
Changed "Convert Json Into Kotlin Class" to "Kotlin data classes from JSON"
resolve #135
> Change Action tip #135

- build.gradle
- src/main/kotlin/extensions/Extension.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/classblockparse/ClassCodeParser.kt
> Polish code and remove deprecated plugin.id

- build.gradle
> Upgrade plugin version

- src/main/kotlin/wu/seal/jsontokotlin/TargetJsonConverter.kt
- src/main/kotlin/wu/seal/jsontokotlin/codeannotations/SerializablePropertyAnnotationTemplate.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/InterceptorManager.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/annotations/serializable/AddSerializableAnnotationClassImportDeclarationInterceptor.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/annotations/serializable/AddSerializableAnnotationInterceptor.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/AdvancedAnnotationTab.kt
- src/test/kotlin/wu/seal/jsontokotlin/interceptor/annotations/serializable/AddSerializableAnnotationInterceptorTest.kt
add Serializable annotation ,include unit test
> add a feature of kotlinx.serialization

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/wu/seal/jsontokotlin/utils/KotlinDataClassFileGenerator.kt
> 3.4.0 bugfix/#193

- src/main/kotlin/extensions/ExtensionsCollector.kt
- src/main/kotlin/extensions/jose/han/ParcelableAnnotationSupport.kt
- src/test/kotlin/extensions/jose/han/ParcelableAnnotationSupportTest.kt
Add extension with a checkbox to enable Parcelable Support would be easy
> Enable Parcelable Support

- src/main/kotlin/wu/seal/jsontokotlin/classscodestruct/Property.kt
- src/main/kotlin/wu/seal/jsontokotlin/codeelements/KProperty.kt
- src/test/kotlin/extensions/ted/zeng/BugTest198.kt
fix error when generating code with json text like {"X\n\nX":1}
> bug fixed #198

- src/main/kotlin/wu/seal/jsontokotlin/ConfigManager.kt
- src/main/kotlin/wu/seal/jsontokotlin/classscodestruct/Property.kt
- src/main/kotlin/wu/seal/jsontokotlin/feedback/Datas.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/FinalKotlinDataClassWrapperInterceptor.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/InterceptorManager.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/AdvancedOtherTab.kt
- src/test/kotlin/wu/seal/jsontokotlin/interceptor/FinalKotlinDataClassWrapperInterceptorTest.kt
> FinalKotlinDataClassWrapperInterceptor is updated

- src/main/kotlin/extensions/wu/seal/ClassNameSuffixSupport.kt
- src/main/kotlin/extensions/wu/seal/PropertyPrefixSupport.kt
- src/main/kotlin/extensions/wu/seal/PropertySuffixSupport.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/JsonInputDialog.kt
- src/main/kotlin/wu/seal/jsontokotlin/ui/NamingConventionDocument.kt
> NamingConvention Filter is added to prefix, suffix and suffix for class name 

- src/main/kotlin/extensions/wu/seal/PropertyPrefixSupport.kt
- src/main/kotlin/extensions/wu/seal/PropertySuffixSupport.kt
> Property.name is checked in Prefix and Suffix support

- build.gradle
- src/main/kotlin/extensions/ExtensionsCollector.kt
- src/main/kotlin/extensions/wu/seal/KeepAnnotationSupportForAndroidX.kt
- src/test/kotlin/extensions/wu/seal/KeepAnnotationSupportForAndroidXTest.kt
> @Keep AndroidX support

- src/main/kotlin/wu/seal/jsontokotlin/IConfigManager.kt
- src/main/kotlin/wu/seal/jsontokotlin/codeannotations/SerializablePropertyAnnotationTemplate.kt
- src/main/kotlin/wu/seal/jsontokotlin/interceptor/annotations/serializable/AddSerializableAnnotationClassImportDeclarationInterceptor.kt
- src/main/kotlin/wu/seal/jsontokotlin/test/TestConfig.kt
- src/test/kotlin/wu/seal/jsontokotlin/KotlinCodeMakerTest.kt
- src/test/kotlin/wu/seal/jsontokotlin/interceptor/annotations/custom/AddCustomAnnotationInterceptorTest.kt
- src/test/kotlin/wu/seal/jsontokotlin/interceptor/annotations/serializable/AddSerializableAnnotationInterceptorTest.kt
Removed the Optional from the Test also
> Remove of Optional in Kotlinx Serialization

- src/main/kotlin/wu/seal/jsontokotlin/model/classscodestruct/DataClass.kt
- src/main/kotlin/wu/seal/jsontokotlin/model/classscodestruct/Property.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/Extensions.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/classgenerator/DataClassGeneratorByJSONSchema.kt
- src/test/kotlin/wu/seal/jsontokotlin/KotlinCodeMakerTest.kt
- src/test/kotlin/wu/seal/jsontokotlin/regression/Issue269Test.kt
fixing Property Nullable Type missing when calling function replaceReferencedClasses() in DataClass.kt
>  Property Nullable Type missing when calling function replaceReferencedClasses() in DataClass.kt 

- README.md
> 📖 add telegram group link to README #327

- src/main/kotlin/wu/seal/jsontokotlin/utils/classgenerator/ListClassGeneratorByJSONArray.kt
- src/test/kotlin/wu/seal/jsontokotlin/regression/Issue334Test.kt
https://github.com/wuseal/JsonToKotlinClass/issues/334
> fix the issue that a double property was recognized as a int property

- src/main/kotlin/wu/seal/jsontokotlin/utils/Extensions.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/classgenerator/GenericListClassGeneratorByJSONArray.kt
- src/main/kotlin/wu/seal/jsontokotlin/utils/classgenerator/ListClassGeneratorByJSONArray.kt
- src/test/kotlin/wu/seal/jsontokotlin/regression/Issue295Test.kt
fix issue 295, solve number types problems fix #295
> fix issue 295, solve number types problems
